name: Test and Release

# Run this job on all pushes and pull requests
# as well as tags with a semantic version
on:
    push:
        branches:
            - "main"
        tags:
            # normal versions
            - "v[0-9]+.[0-9]+.[0-9]+"
            # pre-releases
            - "v[0-9]+.[0-9]+.[0-9]+-**"
    pull_request: {}

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    # Performs quick checks before the expensive test runs
    check-and-lint:
        if: contains(github.event.head_commit.message, '[skip ci]') == false

        runs-on: ubuntu-latest

        steps:
            - uses: ioBroker/testing-action-check@v1
              with:
                  node-version: "18.x"
                  # Uncomment the following line if your adapter cannot be installed using 'npm ci'
                  # install-command: 'npm install'
                  lint: true

    # Runs adapter tests on all supported node versions and OSes
    adapter-tests:
        if: contains(github.event.head_commit.message, '[skip ci]') == false

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x, 24.x]
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: ioBroker/testing-action-adapter@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  os: ${{ matrix.os }}
                  # Uncomment the following line if your adapter cannot be installed using 'npm ci'
                  # install-command: 'npm install'
                  build: false
    # Deploys the final package to NPM
    deploy:
        needs: [check-and-lint, adapter-tests]

        # Trigger this step only when a commit on any branch is tagged with a version number
        if: |
            contains(github.event.head_commit.message, '[skip ci]') == false &&
            github.event_name == 'push' &&
            startsWith(github.ref, 'refs/tags/v')

        runs-on: ubuntu-latest

        # Write permissions are required to create Github releases
        permissions:
            contents: write
            id-token: write

        steps:
            - uses: ioBroker/testing-action-deploy@v1
              with:
                  node-version: "18.x"
                  # Uncomment the following line if your adapter cannot be installed using 'npm ci'
                  # install-command: 'npm install'
                  build: false
                  # npm-token: ${{ secrets.NPM_TOKEN }}  # Commented out for migration to Trusted Publishing
                  github-token: ${{ secrets.GITHUB_TOKEN }}
